arquillian/smart-testing

surefire-provider/src/main/java/org/arquillian/smart/testing/surefire/provider/SmartTestingSurefireProvider.java
=> Improves regex for strategy parameters

core/pom.xml, core/src/main/java/org/arquillian/smart/testing/GitRunnerProperties.java, core/src/test/java/org/arquillian/smart/testing/GitRunnerPropertiesTest.java, pom.xml, strategies/affected/src/main/java/org/arquillian/smart/testing/strategies/affected/AffectedChangesDetectorFactory.java, strategies/changed/src/main/java/org/arquillian/smart/testing/vcs/git/ChangedFilesDetectorFactory.java, strategies/changed/src/main/java/org/arquillian/smart/testing/vcs/git/NewFilesDetectorFactory.java
=> Adds support for git.lastcommits system property.

strategies/affected/src/main/java/org/arquillian/smart/testing/strategies/affected/AffectedChangesDetector.java, strategies/affected/src/main/java/org/arquillian/smart/testing/strategies/affected/AffectedChangesDetectorFactory.java, strategies/affected/src/main/java/org/arquillian/smart/testing/strategies/affected/ClassFileIndex.java, strategies/affected/src/main/java/org/arquillian/smart/testing/strategies/affected/JavaToClassLocation.java, strategies/affected/src/main/java/org/arquillian/smart/testing/strategies/affected/detector/FileSystemTestClassDetector.java, strategies/affected/src/test/java/org/arquillian/smart/testing/strategies/affected/AffectedChangesDetectorTest.java, strategies/affected/src/test/java/org/arquillian/smart/testing/strategies/affected/ClassFileIndexTest.java, strategies/affected/src/test/java/org/arquillian/smart/testing/strategies/affected/fakeproject/test/MyBusinessObjectTestCase.java
=> Now detecting all affected tests for main class changes as per includes

strategies/changed/src/main/java/org/arquillian/smart/testing/vcs/git/AllChangedFilesDetector.java, strategies/changed/src/main/java/org/arquillian/smart/testing/vcs/git/ChangedFilesDetector.java, strategies/changed/src/main/java/org/arquillian/smart/testing/vcs/git/GitChangesDetector.java, strategies/changed/src/main/java/org/arquillian/smart/testing/vcs/git/NewFilesDetector.java
Ability to fetch all git changes at once.
- Refactoring of change detectors.
**Fixes**: #11
=> [WIP]Refactors change detector.

.gitignore, .mvn/extensions.xml, .mvn/maven.config
* Adds [parallel builds](https://cwiki.apache.org/confluence/display/MAVEN/Parallel+builds+in+Maven+3)
* Switches maven build planner to [Takari Smart Builder](http://takari.io/book/30-team-maven.html#takari-smart-builder)
* Introduces [Takari Local Repository](http://takari.io/book/30-team-maven.html#concurrent-safe-local-repository) enabling safe concurrent use of the local repository
=> Maven build speed up

core/src/main/java/org/arquillian/smart/testing/Configuration.java, functional-tests/test-bed/pom.xml, functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/project/MavenExtensionRegisterer.java, functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/project/Project.java, functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/project/ProjectConfigurator.java, mvn-extension/src/main/java/org/arquillian/smart/testing/mvn/ext/ExtensionVersion.java
=> fix(#54): Version is configurable using version method

.travis.yml, functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/project/Project.java, functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/project/ProjectConfigurator.java, functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/rules/GitClone.java, functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/rules/TestBed.java, functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/affected/ChangesOnDifferentModulesAffectedTestsSelectionExecutionFunctionalTest.java, functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/affected/HistoricalChangesAffectedTestsSelectionExecutionFunctionalTest.java, functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/affected/LocalChangesAffectedTestsSelectionExecutionFunctionalTest.java, functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/configuration/DisabledSmartTestingFunctionalTest.java, functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/mixed/LocalChangesMixedStrategySelectionExecutionFunctionalTest.java, functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/newtests/HistoricalChangesNewTestsSelectionExecutionFunctionalTest.java, functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/newtests/LocalChangesNewTestsSelectionExecutionFunctionalTest.java, functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/testbed/ProjectPersistTest.java, pom.xml
Allows test bed user to set using failsafe plugin instead of surefire
Closes #53
=> feat(#53): Allows test bed user to set using failsafe plugin

functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/project/BuildConfigurator.java, functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/project/Project.java, functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/project/ProjectBuilder.java, functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/project/ProjectConfigurator.java, functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/affected/ChangesOnDifferentModulesAffectedTestsSelectionExecutionFunctionalTest.java, functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/affected/HistoricalChangesAffectedTestsSelectionExecutionFunctionalTest.java, functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/affected/LocalChangesAffectedTestsSelectionExecutionFunctionalTest.java, functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/configuration/DisabledSmartTestingFunctionalTest.java, functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/mixed/LocalChangesMixedStrategySelectionExecutionFunctionalTest.java, functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/newtests/HistoricalChangesNewTestsSelectionExecutionFunctionalTest.java, functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/newtests/LocalChangesNewTestsSelectionExecutionFunctionalTest.java
- Refactors `ProjectBuilder` to separate build configuration.  
- Updates functional tests.
Fixes #61
=> Improves build configuration DSL

surefire-provider/src/main/java/org/arquillian/smart/testing/surefire/provider/SmartTestingSurefireProvider.java, surefire-provider/src/test/java/org/arquillian/smart/testing/surefire/provider/SmartTestingProviderTest.java
This is a test that verifies the provider's logic - calling of the delegated provider. 
It is a test for changes introduced in this PR: https://github.com/arquillian/smart-testing/pull/87
=> chore(provider test) Test verifying calling/delegation of getSuites and invoke methods

docs/developing.adoc, functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/rules/TestBed.java, functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/testbed/ProjectPersistTest.java, functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/testbed/ProjectPersistUsingPropertyTest.java
=> fix(#104): creates unique folder for each test project in Test Bed

mvn-extension/src/main/java/org/arquillian/smart/testing/mvn/ext/MavenProjectConfigurator.java
Removing redundant code related to plugin configuration
=> Removed redundant code for plugin configuration properties.

functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/project/ProjectBuilder.java, functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/project/TestResults.java, functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/testresults/SurefireReportReader.java, functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/affected/ChangesOnDifferentModulesAffectedTestsSelectionExecutionFunctionalTest.java, functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/affected/HistoricalChangesAffectedTestsSelectionExecutionFunctionalTest.java, functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/affected/LocalChangesAffectedTestsSelectionExecutionFunctionalTest.java, functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/configuration/DisabledSmartTestingFunctionalTest.java, functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/configuration/SkipTestExecutionFunctionalTest.java, functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/configuration/SpecificTestClassExecutionFunctionalTest.java, functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/configuration/SurefireForksConfigurationTest.java, functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/failed/HistoricalChangesFailedTestsSelectionExecutionFunctionalTest.java, functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/failed/LocalChangesFailedTestsSelectionExecutionFunctionalTest.java, functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/failed/TestReportHandler.java, functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/mixed/LocalChangesMixedStrategySelectionExecutionFunctionalTest.java, functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/newtests/HistoricalChangesNewTestsSelectionExecutionFunctionalTest.java, functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/newtests/LocalChangesNewTestsSelectionExecutionFunctionalTest.java
=> Exposes all test results from the build execution

.asciidoctor/generate.sh, .travis.yml, README.adoc
Provides a convenient script for generating docs so it can be used by contributors and on CI server.
Fixes #163
=> docs: introduces script for generating docs

mvn-extension/src/main/java/org/arquillian/smart/testing/mvn/ext/dependencies/DependencyResolver.java
=> fix(#167): introduces meaningful exception when strategy misspelled

mvn-extension/src/main/java/org/arquillian/smart/testing/mvn/ext/SmartTestingMavenConfigurer.java
Adds shutdown hook to cleanup `.smart-testing` folder when the build is canceled (using `crlt+c`)
See https://docs.oracle.com/javase/7/docs/api/java/lang/Runtime.html#addShutdownHook(java.lang.Thread) to learn which cases we are able to handle with this approach.
Fixes #168
=> fix(#168): adds shutdown hook to cleanup .smart-testing folder

core/src/main/java/org/arquillian/smart/testing/impl/ConfiguredSmartTestingImpl.java, surefire-provider/src/test/java/org/arquillian/smart/testing/surefire/provider/SmartTestingProviderTest.java
=> fix(NPE in test) Added missing mock in SmartTestingProviderTest

docs/configuration.adoc, docs/usage.adoc
- `LAST_COMMITS=3` is equal to `HEAD~~~`
-  `Configuration#modes` resulting to `configuration.html#modes` which is `404`. Now pointing to `index.html#modes`
=> Small fix in documentation

install.sh
=> feat(script) Install script checks if there is a pom.xml file in the directory

mvn-extension/src/main/java/org/arquillian/smart/testing/mvn/ext/MavenProjectConfigurator.java, mvn-extension/src/main/java/org/arquillian/smart/testing/mvn/ext/SmartTestingMavenConfigurer.java
- Removes redundant code for ST configuration in pom.xml for initial approach.
- Corrected string concatenation to log correct message.
=> Remove redundant code & fix string concatenation

core/src/main/java/org/arquillian/smart/testing/scm/git/GitChangeResolver.java, core/src/test/java/org/arquillian/smart/testing/scm/git/GitChangeResolverTest.java
- Checking for any commit existence before finding all commit changes
Fixes #217
=> fixes if repository doesn't contains any commit

functional-tests/test-bed/pom.xml, pom.xml
updated:
* SWR to 3.0.0-beta-2
* SnakeYAML to 1.19
* Mockito to 2.11.0
=> Dependency updates

core/src/main/java/org/arquillian/smart/testing/configuration/ConfigurationLoader.java, core/src/test/java/org/arquillian/smart/testing/configuration/ConfigurationTest.java
=> Fixes NPE for empty config file.

core/pom.xml, functional-tests/git-rules/pom.xml, functional-tests/test-bed/pom.xml, junit-test-result-parser/pom.xml, mvn-extension/pom.xml, pom.xml, strategies/affected/pom.xml, strategies/categorized/pom.xml, strategies/changed/pom.xml, strategies/failed/pom.xml, surefire-provider/pom.xml
Adds missing tests scope for all tests dependencies.
Fixes #285
=> fix(#285): adds missing tests scope for all tests dependencies.

core/src/test/java/org/arquillian/smart/testing/configuration/ConfigurationTest.java, core/src/test/java/org/arquillian/smart/testing/configuration/ConfigurationUsingPropertyTest.java, core/src/test/resources/configuration/dumped-smart-testing.yml
=> refactor(#284): refactors ConfigurationTest and ConfigurationUsingPropertTest

core/src/test/java/org/arquillian/smart/testing/configuration/ConfigurationOverwriteUsingInheritTest.java, core/src/test/java/org/arquillian/smart/testing/configuration/ConfigurationOverwriteUsingInheritWithSystemPropertyTest.java, core/src/test/java/org/arquillian/smart/testing/custom/assertions/ConfigurationAssert.java, core/src/test/java/org/arquillian/smart/testing/custom/assertions/CoreSoftAssertions.java, core/src/test/java/org/arquillian/smart/testing/custom/assertions/CustomSoftAssertions.java, core/src/test/java/org/arquillian/smart/testing/custom/assertions/DirectoryAssert.java, core/src/test/java/org/arquillian/smart/testing/hub/storage/LocalStorageTest.java, mvn-extension/src/test/java/org/arquillian/smart/testing/mvn/ext/checker/SkipInstallationCheckerTest.java, mvn-extension/src/test/java/org/arquillian/smart/testing/mvn/ext/custom/assertions/MavenExtensionSoftAssertions.java, mvn-extension/src/test/java/org/arquillian/smart/testing/mvn/ext/custom/assertions/SkipInstallationCheckerAssert.java, surefire-provider/src/test/java/org/arquillian/smart/testing/surefire/provider/custom/assertions/CustomProviderAssert.java, surefire-provider/src/test/java/org/arquillian/smart/testing/surefire/provider/custom/assertions/SurefireProviderSoftAssertions.java, surefire-provider/src/test/java/org/arquillian/smart/testing/surefire/provider/info/CustomProviderInfoTest.java
Introduces custom assertions across the whole project.
- implemented new custom assertions for core, maven-extension and surefire-provider.
Fixes #290
=> chore(#290): introduces new custom assertions across the project.

.travis.yml
Downloads Maven before executing build
Fixes #323
=> fix(#323): downloads Maven before starting the build on travis

pom.xml
=> fix(#326): releasing also test jars
