arquillian/smart-testing

- surefire-provider/src/main/java/org/arquillian/smart/testing/surefire/provider/TestStrategyApplier.java
- surefire-provider/src/main/java/org/arquillian/smart/testing/surefire/provider/info/TestNgProviderInfo.java
- surefire-provider/src/test/java/org/arquillian/smart/testing/surefire/provider/TestStrategyApplierTest.java
It checks if it is in the list (`TestToRun`) that was previously retrieved when the classpath was scanned.
> fix(#23) Applier checks if the returned test classes should be really run

- surefire-provider/src/main/java/org/arquillian/smart/testing/surefire/provider/LoaderVersionExtractor.java
- surefire-provider/src/main/java/org/arquillian/smart/testing/surefire/provider/ProviderList.java
- surefire-provider/src/main/java/org/arquillian/smart/testing/surefire/provider/ProviderParametersParser.java
- surefire-provider/src/main/java/org/arquillian/smart/testing/surefire/provider/info/JUnit4ProviderInfo.java
- surefire-provider/src/main/java/org/arquillian/smart/testing/surefire/provider/info/JUnitCoreProviderInfo.java
- surefire-provider/src/main/java/org/arquillian/smart/testing/surefire/provider/info/TestNgProviderInfo.java
- surefire-provider/src/test/java/org/arquillian/smart/testing/surefire/provider/LoaderVersionExtractorJUnitTest.java
- surefire-provider/src/test/java/org/arquillian/smart/testing/surefire/provider/LoaderVersionExtractorSurefireBooterTest.java
- surefire-provider/src/test/java/org/arquillian/smart/testing/surefire/provider/LoaderVersionExtractorTestNgTest.java
- surefire-provider/src/test/java/org/arquillian/smart/testing/surefire/provider/ProviderParameterParserTest.java
Instead of taking versions from parameter list it finds a corresponding manifest file (according to groupId and artifactId) and takes version from the path of this file.
I had also a solution that was taking versions directly from the file (manifest) but for example JUnit 4.11 doesn't contain any information about the version there. This is why I'm parsing the file path.
>  feat(#25) Implemented loader version extractor

- functional-tests/test-bed/pom.xml
- functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/project/Project.java
- functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/project/ProjectBuilder.java
- functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/TestBedTemplate.java
- functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/affected/HistoricalChangesAffectedTestsSelectionExecutionFunctionalTest.java
- functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/newtests/HistoricalChangesNewTestsSelectionExecutionFunctionalTest.java
This feature brings the ability to execute embedded build in Test Bed in the debug mode. This gives is better analysis of the build execution, as it lets us connect to the build execution to analyze behaviour of our extension in the runtime,
Enhanced project configuration DSL for enabling debug mode directly in the code:
```java
final List<TestResult> actualTestResults = project
.buildOptions()
.withRemoteDebugging()
.withRemoteSurefireDebugging()
.withDebugOutput()
.configure()
.build();
```
Setting up any of the debugging modes would set agent in suspend mode for both maven execution and surefire execution, thus giving you time to attach debuggers to both.
But this can be also achieved through system properties which you can set as part of your "Run Configuration" in the IDE. Following …
> Debug modes for Test Bed embedded build.

- .travis.yml
- functional-tests/test-bed/pom.xml
- functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/project/ProjectBuilder.java
Introduces ability to specify arbitrary Maven distribution to run embedded mvn builds through environment variable `TEST_BED_M2_HOME`.
Tried other attempts, but these were leading to errors, as explained below.
`embeddedMaven.useMaven3Version("3.3.9")` leads to error on Travis:
```
should_only_execute_tests_related_to_single_local_change_in_production_code_when_affected_is_enabled(org.arquillian.smart.testing.ftest.affected.LocalChangesAffectedTestsSelectionExecutionFunctionalTest)  Time elapsed: 2.522 sec  <<< ERROR!
java.lang.IllegalStateException: Something bad happened when the file: /home/travis/.arquillian/resolver/maven/apache-maven-3.3.9-bin.tar.gz was being extracted. For more information see the stacktrace
```
```
Caused by: …
```
> Travis and Test Bed enhacement

- surefire-provider/src/main/java/org/arquillian/smart/testing/surefire/provider/SmartTestingSurefireProvider.java
In the case of not reusing forks:
`<reuseForks>false</reuseForks>`
surefire calls `getSuites` and calls the method invoke on new provider instance for each item in the getSuites response. This means that the test set retrieved from `getSuites` is already ordered/selected.
When surefire pass the test set to the invoke method it takes that one. Again, it is simulating the way that it is done in original surefire providers
> fix(not reusing fork) ordering/selecting of test classes is moved to getSuites method

- mvn-extension/src/main/java/org/arquillian/smart/testing/mvn/ext/ApplicablePlugins.java
- mvn-extension/src/main/java/org/arquillian/smart/testing/mvn/ext/MavenProjectConfigurator.java
- mvn-extension/src/main/java/org/arquillian/smart/testing/mvn/ext/PreBuildTestOptimizer.java
- surefire-provider/pom.xml
Our `smart-testing-surefire-provider` uses the `surefire-api` dependency (2.19.1 version). If the user uses a newer version of surefire plugin, then it throws this exception:
`java.lang.ClassNotFoundException: org.apache.maven.plugin.surefire.log.api.ConsoleLogger`
The reason is that this class has been moved to a new module `surefire-logger-api` which is (in a normal way) transitively fetched. Since our smart-testing-provider has this dependency in the list of dependencies, then the version `2.19.1` is transitively fetched and (thus) the new logger module is missing.
This is why I have to add the `surefire-api`dependency to the project `Model`- to override the our one.
> fix(surefire 2.20 compatibility) extension adds surefire-api dependency to the list of dependencies

- surefire-provider/src/main/java/org/arquillian/smart/testing/surefire/provider/LoaderVersionExtractor.java
- surefire-provider/src/main/java/org/arquillian/smart/testing/surefire/provider/info/JUnit4ProviderInfo.java
- surefire-provider/src/main/java/org/arquillian/smart/testing/surefire/provider/info/JUnitCoreProviderInfo.java
- surefire-provider/src/main/java/org/arquillian/smart/testing/surefire/provider/info/TestNgProviderInfo.java
- surefire-provider/src/test/java/org/arquillian/smart/testing/surefire/provider/LoaderVersionExtractorSurefireApiTest.java
Previously, I was using `surefire-booter` jar for this retrieval, but the jar is not available in some cases - eg. when:
`<reuseForks>false</reuseForks>`
is set
> fix(surefire version) gets the version from manifest file of surefire-api jar

- surefire-provider/src/main/java/org/arquillian/smart/testing/surefire/provider/SurefireDependencyResolver.java
in the same way, it is done in Surefire when an instance of the provider is created. 
Otherwise. it would fail with 
`NoClassDefFoundError: org/junit/runner/notification/RunNotifier`
as it cannot find the necessary JUnit jar.
> fix(classloader) For loading provider class it uses context classloader of the current thread

- surefire-provider/src/main/java/org/arquillian/smart/testing/surefire/provider/ProviderParametersParser.java
- surefire-provider/src/test/java/org/arquillian/smart/testing/surefire/provider/ProviderParameterParserTest.java
The reason is that when `reuseForks=fales` or `threadCount=0` then the parameters(`includes` & `excludes`) are not available in the `providerProperties`
> fix(forks) Includes and excludes has to be taken from directoryScannerParameters

- strategies/affected/src/main/java/org/arquillian/smart/testing/strategies/affected/AffectedTestsDetector.java
- strategies/affected/src/main/java/org/arquillian/smart/testing/strategies/affected/ClassFileIndex.java
- strategies/affected/src/main/java/org/arquillian/smart/testing/strategies/affected/JavaElement.java
- strategies/affected/src/main/java/org/arquillian/smart/testing/strategies/affected/ast/AbstractJavaClass.java
- strategies/affected/src/main/java/org/arquillian/smart/testing/strategies/affected/ast/JavaAssistClass.java
- strategies/affected/src/main/java/org/arquillian/smart/testing/strategies/affected/ast/JavaAssistClassParser.java
- strategies/affected/src/main/java/org/arquillian/smart/testing/strategies/affected/ast/JavaClassBuilder.java
- strategies/affected/src/main/java/org/arquillian/smart/testing/strategies/affected/ast/UnparsableClass.java
- strategies/affected/src/test/java/org/arquillian/smart/testing/strategies/affected/ClassFileIndexTest.java
Abstracts graph elements form JavaAssist to a custom type, so equals does not depend on anything except the information we require.
With this solution we have `JavaElement` class which abstracts us in the case of JavaAssist cannot parse a Java Class because it is out of classloader.
> chore(refactor): Abstracts graph elements form JavaAssist

- docs/developing.adoc
- functional-tests/test-bed/pom.xml
- functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/mixed/LocalChangesMixedStrategySelectionExecutionFunctionalTest.java
- functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/testbed/ProjectPersistTest.java
Improves documentation & test for project-persist feature. 
- Adds more elaborative information for Project Persistent
- Adds missing test for setting system property `test.bed.project.persist`
- Changed TestBed example to show complete example with class. So user will know we are using Junit rules.
> Improved documentation for project-persist

- core/src/main/java/org/arquillian/smart/testing/TestSelection.java
- core/src/test/java/org/arquillian/smart/testing/TestSelectionTest.java
Adds test for TestSelection
- Adds tests for `TestSelection`
- Changed `HashSet` to `LinkedHashSet` to preserve the order, So we can use it reports with same order as user defined in strategy
- 
Fixes #
> Adds tests for TestSelection

- core/src/main/java/org/arquillian/smart/testing/spi/TestExecutionPlannerFactory.java
- strategies/affected/src/main/java/org/arquillian/smart/testing/strategies/affected/AffectedChangesDetectorFactory.java
- strategies/changed/src/main/java/org/arquillian/smart/testing/vcs/git/ChangedFilesDetectorFactory.java
- strategies/changed/src/main/java/org/arquillian/smart/testing/vcs/git/NewTestsDetectorFactory.java
- strategies/failed/src/main/java/org/arquillian/smart/testing/strategies/failed/FailedTestsDetectorFactory.java
- surefire-provider/src/main/java/org/arquillian/smart/testing/surefire/provider/SmartTestingSurefireProvider.java
- surefire-provider/src/main/java/org/arquillian/smart/testing/surefire/provider/TestExecutionPlannerLoader.java
- surefire-provider/src/main/java/org/arquillian/smart/testing/surefire/provider/TestStrategyApplier.java
- surefire-provider/src/test/java/org/arquillian/smart/testing/surefire/provider/TestExecutionPlannerLoaderTest.java
Removes code not used/redundant because of changes in affected strategy, glob patterns are not used anymore in any strategy.
- Removes glob pattern logic
- Removes check in `TestStrategyApplier` of `testInRun` check since now affected also uses `TestVerifier`
Fixes #109
> chore(remove_code): Removes code not used/redundant 

- core/src/main/java/org/arquillian/smart/testing/Configuration.java
- functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/project/BuildConfigurator.java
- functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/project/Project.java
- functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/project/ProjectBuilder.java
- functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/configuration/DisabledSmartTestingFunctionalTest.java
- functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/configuration/SkipTestExecutionFunctionalTest.java
- mvn-extension/src/main/java/org/arquillian/smart/testing/mvn/ext/MavenProjectConfigurator.java
- mvn-extension/src/main/java/org/arquillian/smart/testing/mvn/ext/MavenPropertyResolver.java
- mvn-extension/src/main/java/org/arquillian/smart/testing/mvn/ext/SmartTestingMavenConfigurer.java
- Check for `maven.test.skip`, `skipTests` and `skipITs` property honored by Surefire and Failsafe plugins. 
- Ignore smart-testing-extension registration/configuration.
- Tests to verify the change depending on the logger message. 
Fixes #73
> Disables extension when test execution is skipped

- functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/project/ProjectBuilder.java
- functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/configuration/SurefireForksConfigurationTest.java
- surefire-provider/src/main/java/org/arquillian/smart/testing/surefire/provider/SmartTestingSurefireProvider.java
This fix solves the remaining issue when using Smart Testing provider with forked surefires.
What I have noticed during the analysis of this problem is that provider is executed on both sides - the main thread (booter) and forked processes. It can happen that the forked process might have none tests passed (probably) but then we are marking execution of this process as completed with result `noTestsToRun` and we don't call actual provider (delegate). This somehow seems to break the protocol (shared output stream) between fork booter and surefire forks. Thus we have `NoSuchElementException` as we prematurely mark process as finishedin the `CommandReader`
- Removes now not needed check if `orderedTests` contain any elements and mark execution as finished with no tests to run. It was …
> Fixes build execution when using multiple forks

- functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/rules/GitClone.java
- functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/rules/TestBed.java
The previous implementation didn't clean up cloned repository properly using `deleteOnExit`
- deletes files and git directory immediately on `after` phase
- minor improvements to clone logic.
> Removes cloned directory from tmp after test execution

- .travis.yml
- docs/usage.adoc
Update documentation with Asciidoctor copy to clipboard extension so user only need to push a button to copy to clipboard the command
- Use of copy to clipboard extension
Fixes #154
> docs: updates documentation with copy to clipboard extension

- functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/configuration/Strategy.java
- functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/project/Project.java
- functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/configuration/MisspelledStrategiesFunctionalTest.java
- mvn-extension/src/main/java/org/arquillian/smart/testing/mvn/ext/dependencies/DependencyResolver.java
- mvn-extension/src/main/java/org/arquillian/smart/testing/mvn/ext/dependencies/StringSimilarityCalculator.java
- mvn-extension/src/test/java/org/arquillian/smart/testing/mvn/ext/dependencies/StringSimilarityCalculatorTest.java
With #171 we introduced an exception informing about not existing strategy. This PR brings a suggestion which one could have been the intended one by still failing the build early, but hinting the user with
```
[ERROR] [Smart Testing Extension] Unable to find strategy [chaenged]. Did you mean [changed]?                                                                                                                                                                                              
[ERROR] [Smart Testing Extension] Unable to find strategy [neew]. Did you mean [new]?                                                                                                                                                                                                      
[ERROR] Internal …
```
> Suggests closest matching strategy when mistyped

- docs/configuration.adoc
- docs/refcard.adoc
- strategies/affected/src/main/java/org/arquillian/smart/testing/strategies/affected/AffectedRunnerProperties.java
- strategies/affected/src/main/java/org/arquillian/smart/testing/strategies/affected/ClassDependenciesGraph.java
- strategies/affected/src/test/java/org/arquillian/smart/testing/strategies/affected/ClassDependenciesGraphTest.java
Adds flag to enable/disable transitivity on affected strategy so in case of big projects containing some "god" classes you can cut the transitivity since affected strategy returns almost all tests to be executed
- Add flag to enable/disable transitivity `smart.testing.affected.transitivity. By default transitivity is enabled.
Fixes: #166
> feat(#166): Adds flag to enable/disable transitivity on affected 

- core/src/main/java/org/arquillian/smart/testing/Configuration.java
- core/src/main/java/org/arquillian/smart/testing/report/ExecutionReportMarshaller.java
- core/src/main/java/org/arquillian/smart/testing/report/SmartTestingReportGenerator.java
- core/src/test/java/org/arquillian/smart/testing/report/ExecutionReporterTest.java
- core/src/test/java/org/arquillian/smart/testing/report/ExecutionReporterUsingPropertyTest.java
- core/src/test/resources/sample-report.xml
- docs/reports.adoc
- functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/configuration/SurefireForksConfigurationTest.java
Changes:
* changed storage directory to: `target/smart-testing/reporting/`
* changed report name to: `report.xml` - IMHO the original `smart-testing-report.xml` had duplicated information that is contained in the directory where the report is stored.
* for storing the report file, I'm using `LocalStorage` logic proposed by: https://github.com/arquillian/smart-testing/pull/159
* removed properties: `smart.testing.report.dir` & `smart.testing.report.name`
Changes proposed by this PR is contained in the commit: https://github.com/arquillian/smart-testing/pull/161/commits/253fb4cd3fce1ac987911b35f8c8076124345cb1
fixes: https://github.com/arquillian/smart-testing/issues/158
> Moved report to target/smart-testing/reporting/report.xml

- strategies/affected/src/main/java/org/arquillian/smart/testing/strategies/affected/AffectedRunnerProperties.java
- strategies/affected/src/main/java/org/arquillian/smart/testing/strategies/affected/ClassDependenciesGraph.java
- strategies/affected/src/test/java/org/arquillian/smart/testing/strategies/affected/AffectedRunnerPropertiesTest.java
Made the `AffectedRunnerProperties` a normal class with a constructor to not share its state (the properties variable) between modules in a non-thread-safe way.
And also to make it testable as it was influenced by the test classes executed before `ClassDependenciesGraphTest`
As a side effect the test `ClassDependenciesGraphTest` failed in IDE:
Fixes #179
> fix: made the AffectedRunnerProperties a normal class with constructor

- docs/installation.adoc
- install.sh
Installation script which simplifies getting started experience with our tool. 
`curl -sSL https://git.io/v5jD6 | bash` 
notice that the `git.io` URL in the docs is different - it points to `master` which will be working only after we merge this PR. See the docs for more options or 
1. Creates  `.mvn/extension.xml` with ST configured to latest (using Maven Central metadata) if the extension file does not exist
2. In case `.mvn/extension.xml` has other extensions defined ours is added to it 
3. If our extension is already defined and has older version we ask to overwrite and do it automatically
4. Detects if we can use extension mechanism, otherwise rollback to [pre Maven `3.3.x` version](http://arquillian.org/smart-testing/#_maven_3_1_x) - before merging we have to decide on #175  (for …
> feat(#146): provides installation script

- core/src/main/java/org/arquillian/smart/testing/api/TestVerifier.java
TestVerifier is executed only in Java files
- `TestVerifier` methods return false if given path is not a Java file
Fixes #165
> fix(#165): TestVerifier is executed only in Java files

- .asciidoctor/generate.sh
- .travis.yml
- builds PR version of the documentation under `arquillian.org/smart-testing/pr/${PR}` and shares the link in the PR comment
- builds tagged doc when tag present on the commit
- cleans up closed PR documentation when on master **and** building the doc (so not every time, but frequently enough)
Documentation generation process is triggered if
- in the range of commits any `.adoc` file was changes
- if the commit is tagged (so we can have for the release commit)
- if commit message contains `[gen docs]` directive
Fixes #147
This crazy amount of commits was for testing travis build... next time I will try with [the local image](https://docs.travis-ci.com/user/common-build-problems/#Troubleshooting-Locally-in-a-Docker-Image).
> feat(#147): introduces per-pr docs build and tagged versions

- docs/configuration.adoc
Educate users about `skipAfterFailureCount` property to get fast feedback loop.
- Updated documentation about `skipAfterFailureCount`. Ref https://github.com/arquillian/smart-testing/issues/96#issuecomment-329310444
> Adds information about surefire.skipAfterFailureCount

- functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/project/BuildConfigurator.java
- functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/project/ChangeApplier.java
- functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/project/MavenExtensionFileRegisterer.java
- functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/project/MavenExtensionShadedJarRegisterer.java
- functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/project/ProjectBuilder.java
- functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/project/ProjectConfigurator.java
- functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/project/Using.java
- functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/configuration/DebugModeAndMaven325FunctionalTest.java
- mvn-extension/pom.xml
Excluding jar signatures:
```
META-INF/*.SF
META-INF/*.DSA
META-INF/*.RSA
```
from the shaded jar that is used for maven extension in older Maven versions. 
If they are present, the shaded jar is not properly loaded and Maven extension doesn't work
Fixes #175
> fix(ext) Excluding jar signatures from shaded jar

- docs/installation.adoc
- docs/refcard.adoc
- docs/usage.adoc
Command duplicated in usage example.
- Deletes duplicate command in usage.
- Adds copy to clipboard option for smart testing extension.
Fixes #
> Fixes typo in usage document example.

- functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/customAssertions/BuiltProjectAssert.java
- functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/customAssertions/SmartTestingSoftAssertions.java
Finds effective poms recursively otherwise the test is green when the expected file is not present in one of the submodules.
fixes: #226
> fix(assertions) Finds effective poms recursively

- core/src/main/java/org/arquillian/smart/testing/configuration/Configuration.java
- core/src/main/java/org/arquillian/smart/testing/hub/storage/ChangeStorage.java
- core/src/main/java/org/arquillian/smart/testing/hub/storage/local/LocalChangeStorage.java
- core/src/main/java/org/arquillian/smart/testing/scm/git/GitChangeResolver.java
- core/src/main/java/org/arquillian/smart/testing/scm/spi/ChangeResolver.java
- core/src/test/java/org/arquillian/smart/testing/hub/storage/LocalChangeStorageTest.java
- core/src/test/java/org/arquillian/smart/testing/scm/git/GitChangeResolverTest.java
- mvn-extension/src/main/java/org/arquillian/smart/testing/mvn/ext/SmartTestingMavenConfigurer.java
- strategies/affected/src/main/java/org/arquillian/smart/testing/strategies/affected/AffectedChangesDetectorFactory.java
- strategies/affected/src/main/java/org/arquillian/smart/testing/strategies/affected/AffectedTestsDetector.java
- strategies/affected/src/test/java/org/arquillian/smart/testing/strategies/affected/AffectedTestsDetectorTest.java
- strategies/changed/src/main/java/org/arquillian/smart/testing/vcs/git/ChangedTestsDetector.java
- strategies/changed/src/main/java/org/arquillian/smart/testing/vcs/git/NewTestsDetector.java
- strategies/changed/src/test/java/org/arquillian/smart/testing/vcs/git/ChangedTestsDetectorTest.java
- strategies/changed/src/test/java/org/arquillian/smart/testing/vcs/git/NewTestsGitBasedDetectorTest.java
- strategies/changed/src/test/java/org/arquillian/smart/testing/vcs/git/NoopStorage.java
The classes `ChangeResolver` and `ChangeStorage` are using correct paths set using API method `in`. Similar changes have been applied also to some other parts of the code to have consistent behavior.
Fixes: #228
> fix: ChangeResolver and ChangeStorage are using correct pahts

- core/src/main/java/org/arquillian/smart/testing/api/SmartTesting.java
- core/src/main/java/org/arquillian/smart/testing/impl/ConfiguredSmartTestingImpl.java
- core/src/main/java/org/arquillian/smart/testing/impl/TestExecutionPlannerLoaderImpl.java
- core/src/main/java/org/arquillian/smart/testing/scm/git/GitChangeResolver.java
- core/src/main/java/org/arquillian/smart/testing/scm/spi/ChangeResolver.java
- core/src/main/java/org/arquillian/smart/testing/spi/TestExecutionPlannerFactory.java
- core/src/test/java/org/arquillian/smart/testing/impl/TestExecutionPlannerLoaderTest.java
- functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/affected/HistoricalChangesAffectedTestsSelectionExecutionFunctionalTest.java
- mvn-extension/src/main/java/org/arquillian/smart/testing/mvn/ext/SmartTestingMavenConfigurer.java
- strategies/affected/src/main/java/org/arquillian/smart/testing/strategies/affected/AffectedChangesDetectorFactory.java
- strategies/affected/src/main/java/org/arquillian/smart/testing/strategies/affected/AffectedTestsDetector.java
- strategies/affected/src/test/java/org/arquillian/smart/testing/strategies/affected/AffectedTestsDetectorTest.java
- strategies/changed/src/main/java/org/arquillian/smart/testing/vcs/git/ChangedFilesDetectorFactory.java
- strategies/changed/src/main/java/org/arquillian/smart/testing/vcs/git/ChangedTestsDetector.java
- strategies/changed/src/main/java/org/arquillian/smart/testing/vcs/git/NewTestsDetector.java
- strategies/changed/src/main/java/org/arquillian/smart/testing/vcs/git/NewTestsDetectorFactory.java
- strategies/changed/src/test/java/org/arquillian/smart/testing/vcs/git/ChangedTestsDetectorTest.java
- strategies/changed/src/test/java/org/arquillian/smart/testing/vcs/git/NewTestsGitBasedDetectorTest.java
- strategies/failed/src/main/java/org/arquillian/smart/testing/strategies/failed/FailedTestsDetectorFactory.java
Strategies and related logic use Configuration provided by SmartTesting API.
In addition, ChangeResolver doesn't load config file if not really necessary.
Modified a ftest to check usage of SmartTesting API from different directory than the project root one (which means also without Configuration)
Fixes #231
> fix: Strategies and related logic use Configuration provided by API

- core/src/main/java/org/arquillian/smart/testing/hub/storage/local/DuringExecutionLocalStorage.java
- functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/configuration/SkipTestExecutionFunctionalTest.java
- mvn-extension/src/main/java/org/arquillian/smart/testing/mvn/ext/SkipInstallationChecker.java
- mvn-extension/src/main/java/org/arquillian/smart/testing/mvn/ext/SmartTestingMavenConfigurer.java
- mvn-extension/src/test/java/org/arquillian/smart/testing/mvn/ext/SkipInstallationCheckerTest.java
In the Maven extension, there is verified if any goal invoking test execution is set. Also, if the target is not present (when the session ends) in any of the modules, then it won't be created by ST extension
- Checking if any of the set goals for the build is present in the list:
`{"test", "prepare-package", "package", "pre-integration-test", "integration-test", "post-integration-test", "verify", "install", "deploy", "pre-site", "site", "post-site", "site-deploy"}`
assuming that only these goals can execute a test.
- I'm also checking if any of the provided goals contains colon `:` - for example in the case: 
`org.apache.maven.plugins:maven-surefire-plugin:2.20.1:test`
the check was copied from [Maven internals](https://github.com/apache/maven/blob/master/maven-core/src/main/java/org/apac …
> fix(goals) Extension checks goals set for the build if any test will be executed

- core/src/test/java/org/arquillian/smart/testing/configuration/ConfigurationTest.java
- core/src/test/java/org/arquillian/smart/testing/configuration/ConfigurationUsingPropertyTest.java
- core/src/test/java/org/arquillian/smart/testing/configuration/ResourceLoader.java
Small boyscoutting when going through the YAML configuration code. Having files loaded using classloader makes it independent from how we build the project and where we store resources on the actual file system.
> fix(test): loads resources from classpath not filesystem path

- core/pom.xml
- core/src/main/java/org/arquillian/smart/testing/scm/git/GitChangeResolver.java
- core/src/main/java/org/arquillian/smart/testing/scm/spi/ChangeResolver.java
- core/src/test/java/org/arquillian/smart/testing/scm/git/GitChangeResolverTest.java
- core/src/test/java/org/arquillian/smart/testing/scm/git/GitChangeResolverWithoutGitTest.java
- mvn-extension/src/main/java/org/arquillian/smart/testing/mvn/ext/SmartTestingMavenConfigurer.java
- strategies/affected/src/main/java/org/arquillian/smart/testing/strategies/affected/AffectedTestsDetector.java
- strategies/changed/src/main/java/org/arquillian/smart/testing/vcs/git/ChangedTestsDetector.java
- strategies/changed/src/main/java/org/arquillian/smart/testing/vcs/git/NewTestsDetector.java
We are initializing all implementation of `ChangeResolver` using ServiceLoader. Currently if we tries to initialize `GitChangeResolver` it's failing due to `IllegalArgumentException with gitdir is not present` which we haven't catched in either in constrcutor of `GitChangeResolver` or in `isApplicable` method. 
- Catching IllegalArgumentException in constructor of `GitChangeResolver` & `isApplicable` method to avoid unexpected exception while running tests
Fixes #216
> Initializing git change resolver if dir doesn't contains git folder.

- functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/affected/ChangesOnDifferentModulesAffectedTestsSelectionExecutionFunctionalTest.java
- functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/configurationfile/HistoricalChangesAffectedTestsSelectionExecutionWithConfigFileFunctionalTest.java
- mvn-extension/src/main/java/org/arquillian/smart/testing/mvn/ext/MavenProjectConfigurator.java
Plugin selection done via `apply-to` property throws Illegal State Exception.
- Check for the plugin name `surefire/failsafe` in artifactID.
Fixes #253
> Fixes plugin selection done via 'apply-to' property.

- mvn-extension/src/main/java/org/arquillian/smart/testing/mvn/ext/MavenProjectConfigurator.java
Fixes ambiguous error message conveying version mismatch despite the correct version used for effective plugin selection.  
- refactors plugin selection filters and error messages. 
Fixes #253
> Refactors effective plugin filters and error messages.

- functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/project/MavenExtensionShadedJarRegisterer.java
Otherwise, in IDE it takes the shaded jar from the classpath, where the jar is not complete.
Fixes #259
> fix(test-bed): When shaded jar is being resolved,classpath resolution is disabled

- core/src/main/java/org/arquillian/smart/testing/configuration/Configuration.java
- core/src/main/java/org/arquillian/smart/testing/impl/TestExecutionPlannerLoader.java
- core/src/main/java/org/arquillian/smart/testing/impl/TestExecutionPlannerLoaderImpl.java
- core/src/main/java/org/arquillian/smart/testing/impl/TestStrategyApplierImpl.java
- core/src/test/java/org/arquillian/smart/testing/impl/TestExecutionPlannerLoaderTest.java
- core/src/test/java/org/arquillian/smart/testing/impl/TestStrategyApplierUsingPropertyTest.java
- mvn-extension/src/main/java/org/arquillian/smart/testing/mvn/ext/dependencies/DependencyResolver.java
The autocorrect functionality has to be available in core to have it accessible (applicable) also in other integration implementations such as in Che
- Moved autocorrect functionality from Maven extension (`DependencyResolver.java`) to Core (`Configuration.java`). The `autocorrectStrategies` method is then called from Smart Testing API
Fixes #269
> chore: Refactored & moved autocorrect functionality to Configuration class

- core/src/main/java/org/arquillian/smart/testing/spi/TestResult.java
- strategies/failed/src/main/java/org/arquillian/smart/testing/strategies/failed/FailedTestsDetector.java
- strategies/failed/src/main/java/org/arquillian/smart/testing/strategies/failed/FailedTestsDetectorFactory.java
- strategies/failed/src/main/java/org/arquillian/smart/testing/strategies/failed/InProjectTestReportLoader.java
When the test reports are being loaded it takes into account the location set by API
I have also added some additional constructors to `TestResult` class for easier usage.
Fixes #270
> fix(#270): when loading test reports it reflects location set by API 

- .asciidoctor/generate.sh
While generating docs, I have observed that on my host, asciidoc container could not write to shared/mounted private volume.
Maybe you guys are not facing this issue as you are using docker-ce. But in my case I am using fedora distribution of docker installed using `dnf install docker`
Ref - http://www.projectatomic.io/blog/2016/03/dwalsh_selinux_containers/
> Added -Z flag to work with SELinux

- core/pom.xml
- docs/registering-strategies.adoc
- mvn-extension/pom.xml
- mvn-extension/src/main/java/org/arquillian/smart/testing/mvn/ext/dependencies/MavenCoordinatesResolver.java
- mvn-extension/src/main/java/org/arquillian/smart/testing/mvn/ext/dependencies/StrategyDependencyResolver.java
- mvn-extension/src/main/resources/strategies.properties
- mvn-extension/src/test/java/org/arquillian/smart/testing/mvn/ext/dependencies/DependencyAssertion.java
- mvn-extension/src/test/java/org/arquillian/smart/testing/mvn/ext/dependencies/MavenCoordinatesResolverTest.java
- pom.xml
- strategies/affected/pom.xml
- strategies/changed/pom.xml
- strategies/failed/pom.xml
All strategies are distributed as shaded jars and when they are added to the model, all their transitive dependencies are excluded.
- added shaded plugin configuration to all strategies
- added complete exclusion of transitive deps for all default (shaded) strategy dependencies
- introduced whole coordinate format: `groupId:artifactId:packaging:classifier:version:scope`
Fixes #279
> fix(#279): strategy deps are shaded and excluded their transitive deps

- core/src/main/java/org/arquillian/smart/testing/impl/TestSelector.java
- core/src/main/java/org/arquillian/smart/testing/impl/TestSelectorFromClasses.java
- core/src/main/java/org/arquillian/smart/testing/impl/TestSelectorFromNames.java
- core/src/main/java/org/arquillian/smart/testing/impl/TestStrategyApplierImpl.java
- core/src/main/java/org/arquillian/smart/testing/spi/TestExecutionPlanner.java
- core/src/test/java/org/arquillian/smart/testing/impl/TestExecutionPlannerLoaderTest.java
- core/src/test/java/org/arquillian/smart/testing/impl/TestSelectorTest.java
- core/src/test/java/org/arquillian/smart/testing/impl/TestStrategyApplierUsingPropertyTest.java
- docs/registering-strategies.adoc
- strategies/affected/src/main/java/org/arquillian/smart/testing/strategies/affected/AffectedTestsDetector.java
- strategies/changed/src/main/java/org/arquillian/smart/testing/vcs/git/ChangedTestsDetector.java
- strategies/changed/src/main/java/org/arquillian/smart/testing/vcs/git/NewTestsDetector.java
- strategies/failed/src/main/java/org/arquillian/smart/testing/strategies/failed/FailedTestsDetector.java
The implementations of the strategies didn't have the information about the set of tests that were selected to be executed. In this PR I'm introducing the changes in `TestExecutionPlanner` API that will provide this kind of information.
- in `TestExecutionPlanner`, instead of one method `getTests()` there are two methods:
```java
Collection<TestSelection> selectTestsFromNames(Iterable<String> testsToRun);
Collection<TestSelection> selectTestsFromClasses(Iterable<Class<?>> testsToRun);
```
Fixes #287
> feat(#287): the set of tests-to-run is provided to TestExecutionPlanner implementations

- docs/configfile.adoc
- docs/configuration.adoc
- docs/refcard.adoc
- docs/registering-strategies.adoc
- functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/configuration/Strategy.java
- functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/categorized/CategorizedTestSelectionFunctionalTests.java
- mvn-extension/src/main/resources/strategies.properties
- mvn-extension/src/test/java/org/arquillian/smart/testing/mvn/ext/dependencies/StrategyDependencyResolverTest.java
- pom.xml
- strategies/categorized/pom.xml
- strategies/categorized/src/main/java/org/arquillian/smart/testing/strategies/categorized/CategoriesParser.java
- strategies/categorized/src/main/java/org/arquillian/smart/testing/strategies/categorized/CategorizedConfiguration.java
- strategies/categorized/src/main/java/org/arquillian/smart/testing/strategies/categorized/CategorizedTestsDetector.java
- strategies/categorized/src/main/java/org/arquillian/smart/testing/strategies/categorized/CategorizedTestsDetectorFactory.java
- strategies/categorized/src/main/resources/META-INF/services/org.arquillian.smart.testing.spi.TestExecutionPlannerFactory
- strategies/categorized/src/test/java/org/arquillian/smart/testing/strategies/categorized/CategoriesParserTest.java
- strategies/categorized/src/test/java/org/arquillian/smart/testing/strategies/categorized/CategorizedTestsDetectorTest.java
- strategies/categorized/src/test/java/org/arquillian/smart/testing/strategies/categorized/project/FirstAndSecondCategorizedClass.java
- strategies/categorized/src/test/java/org/arquillian/smart/testing/strategies/categorized/project/FirstCategorizedClass.java
- strategies/categorized/src/test/java/org/arquillian/smart/testing/strategies/categorized/project/NonCategorizedClass.java
- strategies/categorized/src/test/java/org/arquillian/smart/testing/strategies/categorized/project/ThirdCategorizedClass.java
- strategies/categorized/src/test/java/org/arquillian/smart/testing/strategies/categorized/project/categories/FirstCategory.java
- strategies/categorized/src/test/java/org/arquillian/smart/testing/strategies/categorized/project/categories/SecondCategory.java
- strategies/categorized/src/test/java/org/arquillian/smart/testing/strategies/categorized/project/categories/ThirdCategory.java
Introducing `categorized` strategy.  Selects tests based on JUnit 4 annotation `@Category`. This annotation has a list of classes that represent categories - eg:
`@Category(FirstCategory.class, SecondCategory.class)`
* it doesn't expect only fqn of the classes specified in the category, but a simple name can be used as well
* if no category is specified, but the strategy is used, then it selects all classes that contain the annotation, no matter which classes are specified inside of the annotations.
* it is possible to set
* list of categories (fully qualified names or just simple class names)
* case sensitivity (default is non-case sensitive)
* if it should match all specified categories or when one category class is matched then it is enough (default is the second one - when one …
> feat(#283): added categorized strategy

- core/src/main/java/org/arquillian/smart/testing/TestSelection.java
- core/src/main/java/org/arquillian/smart/testing/impl/TestSelector.java
- core/src/main/java/org/arquillian/smart/testing/report/SmartTestingReportGenerator.java
- core/src/test/java/org/arquillian/smart/testing/TestSelectionTest.java
- core/src/test/java/org/arquillian/smart/testing/impl/TestSelectorTest.java
- surefire-provider/src/main/java/org/arquillian/smart/testing/surefire/provider/SecurityUtils.java
- surefire-provider/src/main/java/org/arquillian/smart/testing/surefire/provider/SmartTestingInvoker.java
- surefire-provider/src/main/java/org/arquillian/smart/testing/surefire/provider/SmartTestingSurefireProvider.java
- surefire-provider/src/main/java/org/arquillian/smart/testing/surefire/provider/SurefireProviderFactory.java
- surefire-provider/src/test/java/org/arquillian/smart/testing/surefire/provider/SmartTestingProviderTest.java
- surefire-provider/src/test/java/org/arquillian/smart/testing/surefire/provider/custom/assertions/SurefireProviderSoftAssertions.java
- surefire-provider/src/test/java/org/arquillian/smart/testing/surefire/provider/custom/assertions/TestListResolverAssert.java
This PR brings a support for selecting particular test methods (not only the whole test classes).
The solution is using `TestListResolver` - this class is used by the providers to check and filter any method pattern specified by a user. Unfortunately, it is an immutable object set as a private field inside of another immutable object, so the only way to make it working is using a Java reflection.
This PR contains only a support in Core, next PR introducing a resolution of categories on test methods will show and test a real usage.
- new variable `testMethodNames` in `TestSelection` containing a list of test method names that should be selected. if the list is empty, then the whole class should be executed
- in `TestSelection` class has been also renamed variable `types` to …
> feat(#305): added support for test method selection

- core/src/main/java/org/arquillian/smart/testing/TestSelection.java
- docs/configfile.adoc
- docs/configuration.adoc
- docs/refcard.adoc
- functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/project/TestResults.java
- functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/testresults/TestResult.java
- functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/categorized/CategorizedTestSelectionFunctionalTests.java
- strategies/categorized/src/main/java/org/arquillian/smart/testing/strategies/categorized/AbstractParser.java
- strategies/categorized/src/main/java/org/arquillian/smart/testing/strategies/categorized/CategoriesParser.java
- strategies/categorized/src/main/java/org/arquillian/smart/testing/strategies/categorized/CategorizedConfiguration.java
- strategies/categorized/src/main/java/org/arquillian/smart/testing/strategies/categorized/CategorizedTestsDetector.java
- strategies/categorized/src/main/java/org/arquillian/smart/testing/strategies/categorized/TagsParser.java
- strategies/categorized/src/test/java/org/arquillian/smart/testing/strategies/categorized/CategoriesParserTest.java
- strategies/categorized/src/test/java/org/arquillian/smart/testing/strategies/categorized/CategorizedTestsDetectorTest.java
- strategies/categorized/src/test/java/org/arquillian/smart/testing/strategies/categorized/TagsParserTest.java
- strategies/categorized/src/test/java/org/arquillian/smart/testing/strategies/categorized/custom/assertions/TestSelectionCollectionAssert.java
- strategies/categorized/src/test/java/org/arquillian/smart/testing/strategies/categorized/project/categories/FirstAndSecondCategorizedClass.java
- strategies/categorized/src/test/java/org/arquillian/smart/testing/strategies/categorized/project/categories/FirstCategorizedClass.java
- strategies/categorized/src/test/java/org/arquillian/smart/testing/strategies/categorized/project/categories/NonCategorizedClass.java
- strategies/categorized/src/test/java/org/arquillian/smart/testing/strategies/categorized/project/categories/ThirdCategorizedClass.java
- strategies/categorized/src/test/java/org/arquillian/smart/testing/strategies/categorized/project/categories/WithCategorizedMethodsClass.java
- strategies/categorized/src/test/java/org/arquillian/smart/testing/strategies/categorized/project/tags/FastTaggedClass.java
- strategies/categorized/src/test/java/org/arquillian/smart/testing/strategies/categorized/project/tags/FirstAndSecondTaggedClass.java
- strategies/categorized/src/test/java/org/arquillian/smart/testing/strategies/categorized/project/tags/FirstTaggedClass.java
- strategies/categorized/src/test/java/org/arquillian/smart/testing/strategies/categorized/project/tags/NonTaggedClass.java
- strategies/categorized/src/test/java/org/arquillian/smart/testing/strategies/categorized/project/tags/ThirdTaggedClass.java
- strategies/categorized/src/test/java/org/arquillian/smart/testing/strategies/categorized/project/tags/WithTaggedMethodsClass.java
This is a specific implementation of test method selection for the `categorized` strategy. It is built on top of the implementation proposed in this PR #308 
The resolution works for both JUnit 4 categories and JUnit 5 tags.
- added `smart.testing.categorized.methods` config parameter to disable/enable method recognition (default is `true`)
- changed `AbstractParser` to get categories/tags annotated on test methods; added abstract method `isTestMethod` to check which method is a test method.
- test-bed - slightly modified test result parser to get results on the test method level
Fixes #304
>  feat(304): categorized strategy is resolving also categories specified on test methods

- core/pom.xml
- core/src/main/java/org/arquillian/smart/testing/TestSelection.java
- core/src/main/java/org/arquillian/smart/testing/spi/TestResult.java
- core/src/test/java/org/arquillian/smart/testing/TestSelectionTest.java
- core/src/test/java/org/arquillian/smart/testing/custom/assertions/TestSelectionCollectionAssert.java
- core/src/test/java/org/arquillian/smart/testing/impl/TestStrategyApplierUsingPropertyTest.java
- docs/configfile.adoc
- docs/configuration.adoc
- docs/refcard.adoc
- docs/registering-strategies.adoc
- functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/failed/LocalChangesFailedTestsSelectionExecutionFunctionalTest.java
- pom.xml
- strategies/categorized/pom.xml
- strategies/categorized/src/test/java/org/arquillian/smart/testing/strategies/categorized/CategorizedTestsDetectorTest.java
- strategies/failed/pom.xml
- strategies/failed/src/main/java/org/arquillian/smart/testing/strategies/failed/FailedConfiguration.java
- strategies/failed/src/main/java/org/arquillian/smart/testing/strategies/failed/FailedTestsDetector.java
- strategies/failed/src/main/java/org/arquillian/smart/testing/strategies/failed/FailedTestsDetectorFactory.java
- strategies/failed/src/main/java/org/arquillian/smart/testing/strategies/failed/InProjectTestReportLoader.java
- strategies/failed/src/main/java/org/arquillian/smart/testing/strategies/failed/TestReportLoader.java
- strategies/failed/src/main/java/org/arquillian/smart/testing/strategies/failed/TestResultsFilter.java
- strategies/failed/src/test/java/org/arquillian/smart/testing/strategies/failed/FailedResultsFilterTest.java
- strategies/failed/src/test/java/org/arquillian/smart/testing/strategies/failed/InProjectTestReportLoaderTest.java
Currently, the failed strategy selects the whole test classes no matter how many of the test methods failed in the previous run. This PR brings the support for selecting particular test methods that failed. By default, it is enabled - can be disabled using config property. 
- To reuse the `TestSelectionCollectionAssert` I've moved it to the `core` module and packing it inside of the test-jar
Fixes #306
> feat(#306): failed strategy selects the particular failed test methods

- core/src/main/java/org/arquillian/smart/testing/impl/TestSelector.java
- core/src/test/java/org/arquillian/smart/testing/impl/TestStrategyApplierUsingPropertyTest.java
Small explanation what I'm doing there:
The only change in the src code is this:
```java
final Set<TestSelection> orderedTests = new LinkedHashSet<>();
selectTests().stream()
.forEachOrdered(selection -> orderedTests.add(createSelectionWithoutMethods(selection)));
```
There are two stategies that are supporting test method selection: `failed` & `categorized`. When the `methods` parameter is used there, they select the methods to be executed and set it into the `TestSelection` object. eg:
```java
TestSelection(TestClass, {"firstTestMethod", "thirdTestMethod"}, "failed")
```
The presence of the test method names is then [checked](https://github.com/arquillian/smart-testing/blob/master/surefire-provider/src/main/java/org/arquillian/smart/testing/surefire/provider/SmartTestingSurefireProvider. …
> fix(#314): test method selection is applied only when selecting mode is used

- mvn-extension/pom.xml
- mvn-extension/src/main/java/org/arquillian/smart/testing/mvn/ext/dependencies/DependencyResolver.java
I've removed the runtime dependencies of the strategies from mvn-extension pom file as they are not necessary there. They are there just because of loading strategy configurations, but this can be loaded lazily when they are needed. So, we can minimize the stack of dependencies that is fetched at the very beginning of the Maven build.
Fixes #316
> fix(#316): removed unnecessary runtime dependencies from mvn-extension

- core/src/main/java/org/arquillian/smart/testing/configuration/Configuration.java
- core/src/main/java/org/arquillian/smart/testing/configuration/ConfigurationLoader.java
- core/src/test/java/org/arquillian/smart/testing/configuration/ConfigurationTest.java
- functional-tests/test-bed/pom.xml
- functional-tests/test-bed/src/main/java/org/arquillian/smart/testing/ftest/testbed/project/ProjectConfigurator.java
- functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/categorized/CategorizedTestSelectionFunctionalTests.java
The variable containing a map of raw strategy configs is dumped into the precalculated config as well to make it available for later loading directly from the strategy implementations.
- Renamed `strategiesConfig` to `rawStrategyConfigurations`
- created getter to add the `rawStrategyConfigurations` variable to the dumped file
- fixed test-bed implementation to allow adding strategy configurations
- changed the logic that loads strategy configurations from the file - added a detection when the strategy config is not a map, but a list - eg. in this case:
```yaml
{autocorrect: false, customProviders: [], customStrategies: [], debug: false, disable: false,
strategies: [categorized], strategiesConfiguration: [categorized: {
caseSensitive: false, categories: [LoaderCategory, serviceCategory], …
```
> fix(#318): the variable containing map of strategy configs is dumped as well

- strategies/affected/src/main/java/org/arquillian/smart/testing/strategies/affected/ast/ClassExtractorAnnotationMemberValue.java
- strategies/affected/src/main/java/org/arquillian/smart/testing/strategies/affected/ast/JavaAssistClass.java
- strategies/affected/src/test/java/org/arquillian/smart/testing/strategies/affected/ast/AnnotationAtClassLevelWithClassValue.java
- strategies/affected/src/test/java/org/arquillian/smart/testing/strategies/affected/ast/Import.java
- strategies/affected/src/test/java/org/arquillian/smart/testing/strategies/affected/ast/JavaAssistClassParserTest.java
Scans annotation attributes as well searching for classes.
- Adds a member visitor to find classes defined in annotation fields
Fixes #320
> fix(#320): scans classes defined as annotations attributes

- docs/configfile.adoc
- docs/configuration.adoc
- docs/refcard.adoc
- functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/categorized/CategorizedTestSelectionFunctionalTests.java
- strategies/categorized/src/main/java/org/arquillian/smart/testing/strategies/categorized/AbstractParser.java
- strategies/categorized/src/main/java/org/arquillian/smart/testing/strategies/categorized/CategorizedConfiguration.java
- strategies/categorized/src/test/java/org/arquillian/smart/testing/strategies/categorized/CategoriesParserTest.java
- strategies/categorized/src/test/java/org/arquillian/smart/testing/strategies/categorized/CategorizedTestsDetectorTest.java
- strategies/categorized/src/test/java/org/arquillian/smart/testing/strategies/categorized/TagsParserTest.java
- strategies/categorized/src/test/java/org/arquillian/smart/testing/strategies/categorized/project/categories/Excluded.java
- strategies/categorized/src/test/java/org/arquillian/smart/testing/strategies/categorized/project/categories/Included.java
- strategies/categorized/src/test/java/org/arquillian/smart/testing/strategies/categorized/project/categories/WithExcludedMethodClass.java
- strategies/categorized/src/test/java/org/arquillian/smart/testing/strategies/categorized/project/categories/WithIncludedAndExcludedCategoriesOnMethodsClass.java
- strategies/categorized/src/test/java/org/arquillian/smart/testing/strategies/categorized/project/tags/WithExcludedTagClass.java
This PR implements the possibility to manually exclude test classes/methods from execution based on their category (see #310 )
- added the ``excludedCategories`` into the ``categorized`` configuration
- changed the ``AbstractParser`` logic to support this feature
- added the ``CategorizedTestSelection`` which serves as an information holder to the categorized selection, which then transforms to the ``TestSelection`` using the ``toTestSelection()`` method.
Fixes #
> Categorized exclusions

- .travis.yml
- pom.xml
updated resolver to 3.1.3 with fixed concurrency issue and also dropped Maven download before the travis build. 
The fix for the concurrency issue is here https://github.com/shrinkwrap/resolver/commit/acd2df6af132e77b0c1c79dbaedfde9625859726 - it is introducing a marker file also for the downloading operation - to avoid parallel downloads of the same binary. 
The same issue was possible to reproduce using this test https://github.com/shrinkwrap/resolver/commit/acd2df6af132e77b0c1c79dbaedfde9625859726#diff-1f2230d1084bd1cb53853f951adea62e - so it also verifies that it is fixed now. 
Reproduced & verified also locally so it should work now :-)
Fixes #323
> fix(#323): updated resolver to 3.1.3 with fixed concurrency issue
